# -*- coding: utf-8 -*-
"""kpi_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiXa3PyE6PUOM2O8NfNuRteyDzbDu5yP
"""

import re

KPI_PATTERNS = ["capital ratio", "solvency margin", "liquidity coverage", "risk-weighted assets"]
def extract_kpis(text):
    return [kpi for kpi in KPI_PATTERNS if kpi in text.lower()]