# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiXa3PyE6PUOM2O8NfNuRteyDzbDu5yP
"""

from fastapi import FastAPI, UploadFile
from app.rag_pipeline import build_rag
from app.pdf_loader import load_documents
from app.vectorstore import store_embeddings
from app.kpi_extractor import extract_kpis

app = FastAPI()

@app.post("/analyze")
async def analyze(pdf: UploadFile):
    docs = load_documents(pdf.file)
    vector_db = store_embeddings(docs)
    rag = build_rag(vector_db)
    summary = rag.run("Summarize key obligations under this regulation.")
    kpis = extract_kpis(summary)
    return {"summary": summary, "kpis": kpis}