# -*- coding: utf-8 -*-
"""pdf_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiXa3PyE6PUOM2O8NfNuRteyDzbDu5yP
"""

from langchain.document_loaders import PyPDFLoader

def load_documents(pdf_path):
    loader = PyPDFLoader(pdf_path)
    return loader.load()