# -*- coding: utf-8 -*-
"""ragpipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiXa3PyE6PUOM2O8NfNuRteyDzbDu5yP
"""

from langchain.chains import RetrievalQA
from langchain.llms import OpenAI

def build_rag(vector_db):
    retriever = vector_db.as_retriever(search_kwargs={'k': 3})
    llm = OpenAI(temperature=0)
    chain = RetrievalQA.from_chain_type(
        llm=llm,
        retriever=retriever,
        chain_type="stuff"
    )
    return chain