# -*- coding: utf-8 -*-
"""vectorstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uiXa3PyE6PUOM2O8NfNuRteyDzbDu5yP
"""

from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings

def store_embeddings(docs):
    embeddings = OpenAIEmbeddings()
    return Chroma.from_documents(docs, embeddings)